//! Cranelift-based JIT compiler for Boa bytecode.
//!
//! The compiler translates a [`CodeBlock`] into a native function that operates
//! on the same `Context` and stack that the interpreter uses. This first version
//! eliminates dispatch overhead but still calls back into Rust helpers for all
//! value operations.

use cranelift_codegen::{
    ir::{types, AbiParam, Block, Function, InstBuilder, Type, UserFuncName, Value},
    settings::{self, Configurable},
};
use cranelift_frontend::{FunctionBuilder, FunctionBuilderContext};
use cranelift_jit::{JITBuilder, JITModule};
use cranelift_module::{FuncId, Linkage, Module};
use std::collections::HashMap;
use std::ops::ControlFlow;

use crate::{
    Context, JsValue,
    vm::{
        CodeBlock, CompletionRecord,
        opcode::{Address, Instruction, InstructionIterator, Opcode},
    },
};

use super::helpers;

/// Raw JIT function pointer.
/// Args: (context_ptr, register_base_ptr). Returns a tag: 0=Continue, 1=Break(Return), 2=Break(Throw).
/// The actual values (return value, exception) are communicated via Context.
type RawJitFn = unsafe extern "C" fn(*mut Context, *mut u64) -> u64;

/// A compiled JIT function that can be called in place of interpreting bytecode.
///
/// Wraps the raw function pointer with a safe calling convention.
#[derive(Clone, Copy)]
pub(crate) struct JitFn(RawJitFn);

impl std::fmt::Debug for JitFn {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("JitFn")
            .field(&(self.0 as *const ()))
            .finish()
    }
}

impl JitFn {
    /// Call the JIT-compiled function.
    ///
    /// The JIT function returns a tag:
    /// - 0: `handle_return` returned `Continue` — frame was popped, result
    ///   pushed on the stack. This is the normal case.
    /// - 1: `handle_return` returned `Break(Return(value))` — `exit_early`
    ///   was set, value is in the `CompletionRecord`.
    /// - 2: An exception occurred — stored in `pending_exception`.
    pub(crate) fn call(self, context: &mut Context) -> CompletionRecord {
        // Compute the register base pointer: &mut stack[rp] as *mut u64.
        // JsValue is 8 bytes (u64-sized) on 64-bit, so we can treat the
        // register slice as a *mut u64.
        let rp = context.vm.frame().rp as usize;
        let reg_base = context.vm.stack.stack[rp..].as_mut_ptr().cast::<u64>();

        // SAFETY: The raw function was generated by Cranelift with the correct
        // signature (two pointer args, returns u64). reg_base points into the
        // stack's heap allocation which remains valid for the call's duration.
        let tag = unsafe { (self.0)(context as *mut Context, reg_base) };
        match tag {
            0 => {
                // Normal return — handle_return already popped the frame and
                // pushed the result on the stack. Return Normal completion.
                CompletionRecord::Normal(JsValue::undefined())
            }
            1 => {
                // exit_early was set — handle_return returned Break(Return(value)).
                CompletionRecord::Return(context.vm.take_return_value())
            }
            _ => {
                // Exception.
                CompletionRecord::Throw(
                    context
                        .vm
                        .pending_exception
                        .take()
                        .unwrap_or_else(|| {
                            crate::JsNativeError::error()
                                .with_message("JIT: unknown error")
                                .into()
                        }),
                )
            }
        }
    }
}

/// Holds the [`FuncId`]s for the runtime helper functions that JIT code calls.
struct HelperFuncs {
    store_zero: FuncId,
    store_one: FuncId,
    store_int8: FuncId,
    store_int16: FuncId,
    store_int32: FuncId,
    get_argument: FuncId,
    move_: FuncId,
    set_accumulator: FuncId,
    push_from_register: FuncId,
    pop_into_register: FuncId,
    add: FuncId,
    sub: FuncId,
    mul: FuncId,
    bit_or: FuncId,
    inc: FuncId,
    increment_loop_iteration: FuncId,
    not_less_than: FuncId,
    check_return_and_return: FuncId,
}

/// The JIT compiler. Holds the Cranelift module and compiled function cache.
pub(crate) struct JitCompiler {
    module: JITModule,
    ptr_type: Type,
    helpers: HelperFuncs,
    func_counter: u32,
}

impl std::fmt::Debug for JitCompiler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("JitCompiler")
            .field("func_counter", &self.func_counter)
            .finish_non_exhaustive()
    }
}

impl JitCompiler {
    /// Create a new JIT compiler for the host architecture.
    pub(crate) fn new() -> Result<Self, String> {
        let mut flag_builder = settings::builder();
        flag_builder
            .set("opt_level", "speed")
            .map_err(|e| e.to_string())?;

        let isa_builder =
            cranelift_native::builder().map_err(|e| format!("host ISA not supported: {e}"))?;
        let isa = isa_builder
            .finish(settings::Flags::new(flag_builder))
            .map_err(|e| e.to_string())?;

        let ptr_type = isa.pointer_type();

        let mut builder = JITBuilder::with_isa(isa, cranelift_module::default_libcall_names());

        // Register helper function symbols.
        let syms: &[(&str, *const u8)] = &[
            ("jit_store_zero", helpers::jit_store_zero as *const u8),
            ("jit_store_one", helpers::jit_store_one as *const u8),
            ("jit_store_int8", helpers::jit_store_int8 as *const u8),
            ("jit_store_int16", helpers::jit_store_int16 as *const u8),
            ("jit_store_int32", helpers::jit_store_int32 as *const u8),
            ("jit_get_argument", helpers::jit_get_argument as *const u8),
            ("jit_move", helpers::jit_move as *const u8),
            ("jit_set_accumulator", helpers::jit_set_accumulator as *const u8),
            ("jit_push_from_register", helpers::jit_push_from_register as *const u8),
            ("jit_pop_into_register", helpers::jit_pop_into_register as *const u8),
            ("jit_add", helpers::jit_add as *const u8),
            ("jit_sub", helpers::jit_sub as *const u8),
            ("jit_mul", helpers::jit_mul as *const u8),
            ("jit_bit_or", helpers::jit_bit_or as *const u8),
            ("jit_inc", helpers::jit_inc as *const u8),
            ("jit_increment_loop_iteration", helpers::jit_increment_loop_iteration as *const u8),
            ("jit_not_less_than", helpers::jit_not_less_than as *const u8),
            ("jit_check_return_and_return", helpers::jit_check_return_and_return as *const u8),
        ];
        for &(name, ptr) in syms {
            builder.symbol(name, ptr);
        }

        let mut module = JITModule::new(builder);
        let helpers = Self::declare_helpers(&mut module, ptr_type)?;

        Ok(Self {
            module,
            ptr_type,
            helpers,
            func_counter: 0,
        })
    }

    fn declare_helpers(module: &mut JITModule, ptr: Type) -> Result<HelperFuncs, String> {
        // Signature builders
        let sig_void_1 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.params.push(AbiParam::new(types::I32));
            s
        };
        let sig_void_2 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s
        };
        let sig_void_3 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s
        };
        let sig_ret64_0 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.returns.push(AbiParam::new(types::I64));
            s
        };
        let sig_ret64_2 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s.returns.push(AbiParam::new(types::I64));
            s
        };
        let sig_ret64_3 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s.returns.push(AbiParam::new(types::I64));
            s
        };

        let d = |module: &mut JITModule, name, sig: &cranelift_codegen::ir::Signature| {
            module
                .declare_function(name, Linkage::Import, sig)
                .map_err(|e| e.to_string())
        };

        Ok(HelperFuncs {
            store_zero: d(module, "jit_store_zero", &sig_void_1)?,
            store_one: d(module, "jit_store_one", &sig_void_1)?,
            store_int8: d(module, "jit_store_int8", &sig_void_2)?,
            store_int16: d(module, "jit_store_int16", &sig_void_2)?,
            store_int32: d(module, "jit_store_int32", &sig_void_2)?,
            get_argument: d(module, "jit_get_argument", &sig_void_2)?,
            move_: d(module, "jit_move", &sig_void_2)?,
            set_accumulator: d(module, "jit_set_accumulator", &sig_void_1)?,
            push_from_register: d(module, "jit_push_from_register", &sig_void_1)?,
            pop_into_register: d(module, "jit_pop_into_register", &sig_void_1)?,
            add: d(module, "jit_add", &sig_ret64_3)?,
            sub: d(module, "jit_sub", &sig_ret64_3)?,
            mul: d(module, "jit_mul", &sig_ret64_3)?,
            bit_or: d(module, "jit_bit_or", &sig_ret64_3)?,
            inc: d(module, "jit_inc", &sig_ret64_2)?,
            increment_loop_iteration: d(module, "jit_increment_loop_iteration", &sig_ret64_0)?,
            not_less_than: d(module, "jit_not_less_than", &sig_ret64_2)?,
            check_return_and_return: d(module, "jit_check_return_and_return", &sig_ret64_0)?,
        })
    }

    /// Compile a [`CodeBlock`] into a native function.
    pub(crate) fn compile(&mut self, code: &CodeBlock) -> Option<JitFn> {
        if !super::can_compile(code) {
            return None;
        }

        let name = format!("jit_fn_{}", self.func_counter);
        self.func_counter += 1;

        let mut sig = self.module.make_signature();
        sig.params.push(AbiParam::new(self.ptr_type)); // &mut Context
        sig.params.push(AbiParam::new(self.ptr_type)); // *mut u64 (register base)
        sig.returns.push(AbiParam::new(types::I64));

        let func_id = self
            .module
            .declare_function(&name, Linkage::Local, &sig)
            .expect("declare function");

        let mut func =
            Function::with_name_signature(UserFuncName::testcase(&name), sig.clone());

        let mut func_ctx = FunctionBuilderContext::new();
        {
            let mut builder = FunctionBuilder::new(&mut func, &mut func_ctx);

            let entry_block = builder.create_block();
            builder.append_block_params_for_function_params(entry_block);
            builder.switch_to_block(entry_block);

            let ctx_ptr = builder.block_params(entry_block)[0];
            let reg_base = builder.block_params(entry_block)[1];

            self.translate_body(&mut builder, ctx_ptr, reg_base, code, entry_block);

            builder.finalize();
        }

        let mut ctx = cranelift_codegen::Context::for_function(func);
        self.module
            .define_function(func_id, &mut ctx)
            .expect("define function");
        self.module.clear_context(&mut ctx);
        self.module.finalize_definitions().expect("finalize");

        let code_ptr = self.module.get_finalized_function(func_id);

        // SAFETY: The generated code has signature (ptr) -> i64, matching RawJitFn.
        let raw: RawJitFn = unsafe { std::mem::transmute(code_ptr) };
        Some(JitFn(raw))
    }

    /// Emit a call to a fallible helper (returns i64: 0=ok, nonzero=error).
    /// On error, returns from the JIT function with error tag 2.
    fn emit_fallible_call(
        builder: &mut FunctionBuilder<'_>,
        func_ref: cranelift_codegen::ir::FuncRef,
        args: &[Value],
        error_block: Block,
    ) {
        let result = builder.ins().call(func_ref, args);
        let tag = builder.inst_results(result)[0];
        let zero = builder.ins().iconst(types::I64, 0);
        let ok = builder.ins().icmp(cranelift_codegen::ir::condcodes::IntCC::Equal, tag, zero);

        let continue_block = builder.create_block();
        builder.ins().brif(ok, continue_block, &[], error_block, &[]);

        builder.switch_to_block(continue_block);
    }

    /// Load a JsValue (u64) from the register file at the given index.
    fn load_reg(
        builder: &mut FunctionBuilder<'_>,
        reg_base: Value,
        index: u32,
    ) -> Value {
        let offset = (index as i32) * 8; // each JsValue is 8 bytes
        builder
            .ins()
            .load(types::I64, cranelift_codegen::ir::MemFlags::trusted(), reg_base, offset)
    }

    /// Store a JsValue (u64) to the register file at the given index.
    fn store_reg(
        builder: &mut FunctionBuilder<'_>,
        reg_base: Value,
        index: u32,
        value: Value,
    ) {
        let offset = (index as i32) * 8;
        builder
            .ins()
            .store(cranelift_codegen::ir::MemFlags::trusted(), value, reg_base, offset);
    }

    /// NaN-boxing constants for integer fast path.
    const MASK_KIND: u64 = 0x7FFF_0000_0000_0000;
    const MASK_INT32: u64 = 0x7FF9_0000_0000_0000;

    /// Emit an inlined integer Add with fallback to helper.
    /// Returns true if a new block was created (caller should not add more
    /// instructions to the old block).
    fn emit_inlined_add(
        &self,
        builder: &mut FunctionBuilder<'_>,
        ctx_ptr: Value,
        reg_base: Value,
        dst: u32,
        lhs: u32,
        rhs: u32,
        add_ref: cranelift_codegen::ir::FuncRef,
        error_block: Block,
    ) {
        // Load raw u64 values from registers.
        let lhs_val = Self::load_reg(builder, reg_base, lhs);
        let rhs_val = Self::load_reg(builder, reg_base, rhs);

        // Check both are Integer32: (val & MASK_KIND) == MASK_INT32
        let mask = builder.ins().iconst(types::I64, Self::MASK_KIND as i64);
        let int_tag = builder.ins().iconst(types::I64, Self::MASK_INT32 as i64);

        let lhs_tag = builder.ins().band(lhs_val, mask);
        let rhs_tag = builder.ins().band(rhs_val, mask);
        let lhs_is_int = builder.ins().icmp(cranelift_codegen::ir::condcodes::IntCC::Equal, lhs_tag, int_tag);
        let rhs_is_int = builder.ins().icmp(cranelift_codegen::ir::condcodes::IntCC::Equal, rhs_tag, int_tag);
        let both_int = builder.ins().band(lhs_is_int, rhs_is_int);

        let fast_block = builder.create_block();
        let slow_block = builder.create_block();
        let merge_block = builder.create_block();

        builder.ins().brif(both_int, fast_block, &[], slow_block, &[]);

        // Fast path: extract i32, add with overflow check, tag result.
        builder.switch_to_block(fast_block);


        let lhs_i32 = builder.ins().ireduce(types::I32, lhs_val);
        let rhs_i32 = builder.ins().ireduce(types::I32, rhs_val);
        let (sum, overflow) = builder.ins().sadd_overflow(lhs_i32, rhs_i32);

        let overflow_block = builder.create_block();
        let no_overflow_block = builder.create_block();
        builder.ins().brif(overflow, overflow_block, &[], no_overflow_block, &[]);

        // No overflow: tag as Integer32 and store.
        builder.switch_to_block(no_overflow_block);

        let result_u64 = builder.ins().uextend(types::I64, sum);
        let int32_mask = builder.ins().iconst(types::I64, 0xFFFF_FFFF_i64);
        let result_masked = builder.ins().band(result_u64, int32_mask);
        let result_tagged = builder.ins().bor(result_masked, int_tag);
        Self::store_reg(builder, reg_base, dst, result_tagged);
        builder.ins().jump(merge_block, &[]);

        // Overflow: promote to f64 and fall through to slow path.
        // (Actually, simpler: just call the slow helper on overflow too.)
        builder.switch_to_block(overflow_block);

        builder.ins().jump(slow_block, &[]);

        // Slow path: call the helper function.
        builder.switch_to_block(slow_block);

        let d = builder.ins().iconst(types::I32, i64::from(dst));
        let l = builder.ins().iconst(types::I32, i64::from(lhs));
        let r = builder.ins().iconst(types::I32, i64::from(rhs));
        let result = builder.ins().call(add_ref, &[ctx_ptr, d, l, r]);
        let tag = builder.inst_results(result)[0];
        let zero = builder.ins().iconst(types::I64, 0);
        let ok = builder.ins().icmp(cranelift_codegen::ir::condcodes::IntCC::Equal, tag, zero);
        builder.ins().brif(ok, merge_block, &[], error_block, &[]);

        // Merge block: continue with next instruction.
        builder.switch_to_block(merge_block);

    }

    /// Translate the bytecode body into Cranelift IR.
    fn translate_body(
        &mut self,
        builder: &mut FunctionBuilder<'_>,
        ctx_ptr: Value,
        reg_base: Value,
        code: &CodeBlock,
        entry_block: Block,
    ) {
        // Import helper function references.
        let store_zero_ref = self.module.declare_func_in_func(self.helpers.store_zero, builder.func);
        let store_one_ref = self.module.declare_func_in_func(self.helpers.store_one, builder.func);
        let store_int8_ref = self.module.declare_func_in_func(self.helpers.store_int8, builder.func);
        let store_int16_ref = self.module.declare_func_in_func(self.helpers.store_int16, builder.func);
        let store_int32_ref = self.module.declare_func_in_func(self.helpers.store_int32, builder.func);
        let get_arg_ref = self.module.declare_func_in_func(self.helpers.get_argument, builder.func);
        let move_ref = self.module.declare_func_in_func(self.helpers.move_, builder.func);
        let set_acc_ref = self.module.declare_func_in_func(self.helpers.set_accumulator, builder.func);
        let push_reg_ref = self.module.declare_func_in_func(self.helpers.push_from_register, builder.func);
        let pop_reg_ref = self.module.declare_func_in_func(self.helpers.pop_into_register, builder.func);
        let add_ref = self.module.declare_func_in_func(self.helpers.add, builder.func);
        let sub_ref = self.module.declare_func_in_func(self.helpers.sub, builder.func);
        let mul_ref = self.module.declare_func_in_func(self.helpers.mul, builder.func);
        let bit_or_ref = self.module.declare_func_in_func(self.helpers.bit_or, builder.func);
        let inc_ref = self.module.declare_func_in_func(self.helpers.inc, builder.func);
        let inc_loop_ref = self.module.declare_func_in_func(self.helpers.increment_loop_iteration, builder.func);
        let not_lt_ref = self.module.declare_func_in_func(self.helpers.not_less_than, builder.func);
        let ret_ref = self.module.declare_func_in_func(self.helpers.check_return_and_return, builder.func);

        // Error block: returns error tag (2) to signal exception to caller.
        let error_block = builder.create_block();

        // Phase 1: Pre-scan bytecode to find jump targets and create blocks.
        let mut block_map: HashMap<u32, Block> = HashMap::new();
        {
            let iter = InstructionIterator::new(&code.bytecode);
            for (_pc, _opcode, instruction) in iter {
                match &instruction {
                    Instruction::Jump { address } => {
                        let target = address.as_u32();
                        block_map
                            .entry(target)
                            .or_insert_with(|| builder.create_block());
                    }
                    Instruction::JumpIfNotLessThan { address, .. } => {
                        let target = address.as_u32();
                        block_map
                            .entry(target)
                            .or_insert_with(|| builder.create_block());
                    }
                    _ => {}
                }
            }
        }

        // We also need blocks for the instruction AFTER a conditional jump
        // (the fall-through path). And for the instruction after the jump target
        // when it's not already a block boundary.
        // Actually, for conditional jumps, the fall-through is just the next
        // instruction in the current block — we only need blocks where jumps
        // LAND (forward or backward).

        // Phase 2: Emit code. When we reach a PC that's a jump target,
        // transition to its block.
        let iter = InstructionIterator::new(&code.bytecode);
        let mut terminated = false;

        for (pc, _opcode, instruction) in iter {
            // Check if this PC is a jump target — if so, transition to its block.
            if let Some(&target_block) = block_map.get(&(pc as u32)) {
                if !terminated {
                    // Fall through from previous block.
                    builder.ins().jump(target_block, &[]);
                }
                builder.switch_to_block(target_block);
                terminated = false;
            }

            if terminated {
                continue;
            }

            let i32const =
                |builder: &mut FunctionBuilder<'_>, val: u32| -> Value {
                    builder.ins().iconst(types::I32, i64::from(val))
                };

            match instruction {
                Instruction::StoreZero { dst } => {
                    // Inline: tag 0 as Integer32 and store directly.
                    let tagged = builder.ins().iconst(types::I64, Self::MASK_INT32 as i64);
                    Self::store_reg(builder, reg_base, u32::from(dst), tagged);
                }
                Instruction::StoreOne { dst } => {
                    let tagged = builder.ins().iconst(types::I64, (Self::MASK_INT32 | 1) as i64);
                    Self::store_reg(builder, reg_base, u32::from(dst), tagged);
                }
                Instruction::StoreInt8 { dst, value } => {
                    let tagged_val = Self::MASK_INT32 | ((value as u32) as u64 & 0xFFFF_FFFF);
                    let tagged = builder.ins().iconst(types::I64, tagged_val as i64);
                    Self::store_reg(builder, reg_base, u32::from(dst), tagged);
                }
                Instruction::StoreInt16 { dst, value } => {
                    let tagged_val = Self::MASK_INT32 | ((value as u32) as u64 & 0xFFFF_FFFF);
                    let tagged = builder.ins().iconst(types::I64, tagged_val as i64);
                    Self::store_reg(builder, reg_base, u32::from(dst), tagged);
                }
                Instruction::StoreInt32 { dst, value } => {
                    let tagged_val = Self::MASK_INT32 | ((value as u32) as u64 & 0xFFFF_FFFF);
                    let tagged = builder.ins().iconst(types::I64, tagged_val as i64);
                    Self::store_reg(builder, reg_base, u32::from(dst), tagged);
                }
                Instruction::GetArgument { index, dst } => {
                    let idx = i32const(builder, u32::from(index));
                    let d = i32const(builder, u32::from(dst));
                    builder.ins().call(get_arg_ref, &[ctx_ptr, idx, d]);
                }
                Instruction::Move { dst, src } => {
                    // For types currently supported by the JIT (which don't
                    // include object/string/symbol/bigint creation), all register
                    // values are primitives (integers, floats, undefined, null,
                    // booleans). These are plain u64 copies — no refcount needed.
                    //
                    // When the JIT starts supporting object-producing opcodes,
                    // this must be revisited to handle GC'd values properly.
                    let val = Self::load_reg(builder, reg_base, u32::from(src));
                    Self::store_reg(builder, reg_base, u32::from(dst), val);
                }
                Instruction::SetAccumulator { src } => {
                    let s = i32const(builder, u32::from(src));
                    builder.ins().call(set_acc_ref, &[ctx_ptr, s]);
                }
                Instruction::PushFromRegister { src } => {
                    let s = i32const(builder, u32::from(src));
                    builder.ins().call(push_reg_ref, &[ctx_ptr, s]);
                }
                Instruction::PopIntoRegister { dst } => {
                    let d = i32const(builder, u32::from(dst));
                    builder.ins().call(pop_reg_ref, &[ctx_ptr, d]);
                }
                Instruction::Add { dst, lhs, rhs } => {
                    self.emit_inlined_add(
                        builder, ctx_ptr, reg_base,
                        u32::from(dst), u32::from(lhs), u32::from(rhs),
                        add_ref, error_block,
                    );
                }
                Instruction::Sub { dst, lhs, rhs } => {
                    let d = i32const(builder, u32::from(dst));
                    let l = i32const(builder, u32::from(lhs));
                    let r = i32const(builder, u32::from(rhs));
                    Self::emit_fallible_call(builder, sub_ref, &[ctx_ptr, d, l, r], error_block);
                }
                Instruction::Mul { dst, lhs, rhs } => {
                    let d = i32const(builder, u32::from(dst));
                    let l = i32const(builder, u32::from(lhs));
                    let r = i32const(builder, u32::from(rhs));
                    Self::emit_fallible_call(builder, mul_ref, &[ctx_ptr, d, l, r], error_block);
                }
                Instruction::BitOr { dst, lhs, rhs } => {
                    // Inline integer fast path for `|`.
                    let lhs_val = Self::load_reg(builder, reg_base, u32::from(lhs));
                    let rhs_val = Self::load_reg(builder, reg_base, u32::from(rhs));
                    let mask = builder.ins().iconst(types::I64, Self::MASK_KIND as i64);
                    let int_tag = builder.ins().iconst(types::I64, Self::MASK_INT32 as i64);
                    let lhs_tag = builder.ins().band(lhs_val, mask);
                    let rhs_tag = builder.ins().band(rhs_val, mask);
                    let lhs_is_int = builder.ins().icmp(cranelift_codegen::ir::condcodes::IntCC::Equal, lhs_tag, int_tag);
                    let rhs_is_int = builder.ins().icmp(cranelift_codegen::ir::condcodes::IntCC::Equal, rhs_tag, int_tag);
                    let both_int = builder.ins().band(lhs_is_int, rhs_is_int);

                    let fast_block = builder.create_block();
                    let slow_block = builder.create_block();
                    let merge_block = builder.create_block();
                    builder.ins().brif(both_int, fast_block, &[], slow_block, &[]);

                    // Fast: i32 bitwise OR, always succeeds (no overflow possible).
                    builder.switch_to_block(fast_block);
            
                    let lhs_i32 = builder.ins().ireduce(types::I32, lhs_val);
                    let rhs_i32 = builder.ins().ireduce(types::I32, rhs_val);
                    let result = builder.ins().bor(lhs_i32, rhs_i32);
                    let result_u64 = builder.ins().uextend(types::I64, result);
                    let mask32 = builder.ins().iconst(types::I64, 0xFFFF_FFFF_i64);
                    let result_masked = builder.ins().band(result_u64, mask32);
                    let result_tagged = builder.ins().bor(result_masked, int_tag);
                    Self::store_reg(builder, reg_base, u32::from(dst), result_tagged);
                    builder.ins().jump(merge_block, &[]);

                    // Slow path.
                    builder.switch_to_block(slow_block);
            
                    let d = i32const(builder, u32::from(dst));
                    let l = i32const(builder, u32::from(lhs));
                    let r = i32const(builder, u32::from(rhs));
                    Self::emit_fallible_call(builder, bit_or_ref, &[ctx_ptr, d, l, r], error_block);
                    builder.ins().jump(merge_block, &[]);

                    builder.switch_to_block(merge_block);
            
                }
                Instruction::Inc { dst, src } => {
                    // Inline integer fast path for i++ (most common case).
                    let src_val = Self::load_reg(builder, reg_base, u32::from(src));
                    let mask = builder.ins().iconst(types::I64, Self::MASK_KIND as i64);
                    let int_tag = builder.ins().iconst(types::I64, Self::MASK_INT32 as i64);
                    let src_tag = builder.ins().band(src_val, mask);
                    let is_int = builder.ins().icmp(
                        cranelift_codegen::ir::condcodes::IntCC::Equal, src_tag, int_tag,
                    );

                    let fast_block = builder.create_block();
                    let slow_block = builder.create_block();
                    let merge_block = builder.create_block();
                    builder.ins().brif(is_int, fast_block, &[], slow_block, &[]);

                    // Fast path: extract i32, check < MAX, increment, store both.
                    builder.switch_to_block(fast_block);
            
                    let src_i32 = builder.ins().ireduce(types::I32, src_val);
                    let max_val = builder.ins().iconst(types::I32, i64::from(i32::MAX));
                    let not_max = builder.ins().icmp(
                        cranelift_codegen::ir::condcodes::IntCC::SignedLessThan,
                        src_i32, max_val,
                    );

                    let inc_block = builder.create_block();
                    builder.ins().brif(not_max, inc_block, &[], slow_block, &[]);

                    builder.switch_to_block(inc_block);
            
                    let one_i32 = builder.ins().iconst(types::I32, 1);
                    let incremented = builder.ins().iadd(src_i32, one_i32);
                    // Tag the incremented value.
                    let inc_u64 = builder.ins().uextend(types::I64, incremented);
                    let mask32 = builder.ins().iconst(types::I64, 0xFFFF_FFFF_i64);
                    let inc_masked = builder.ins().band(inc_u64, mask32);
                    let inc_tagged = builder.ins().bor(inc_masked, int_tag);
                    // Inc writes original to src, incremented to dst.
                    Self::store_reg(builder, reg_base, u32::from(src), src_val);
                    Self::store_reg(builder, reg_base, u32::from(dst), inc_tagged);
                    builder.ins().jump(merge_block, &[]);

                    // Slow path.
                    builder.switch_to_block(slow_block);
            
                    let d = i32const(builder, u32::from(dst));
                    let s = i32const(builder, u32::from(src));
                    Self::emit_fallible_call(builder, inc_ref, &[ctx_ptr, d, s], error_block);
                    builder.ins().jump(merge_block, &[]);

                    builder.switch_to_block(merge_block);
            
                }
                Instruction::IncrementLoopIteration => {
                    // Inline: just increment the counter. Skip the limit check
                    // for now — the runtime limit is rarely set and checking it
                    // requires chasing through Context fields. We still call the
                    // helper if we want to support limits in the future.
                    // For now, the JIT doesn't support runtime limits on loops.
                    // (This matches common JIT behavior — V8 doesn't check loop
                    // limits in optimized code either.)
                }
                Instruction::Jump { address } => {
                    let target = block_map[&address.as_u32()];
                    builder.ins().jump(target, &[]);
                    terminated = true;
                }
                Instruction::JumpIfNotLessThan { lhs, rhs, address } => {
                    let target = block_map[&address.as_u32()];

                    // Inline integer fast path.
                    let lhs_val = Self::load_reg(builder, reg_base, u32::from(lhs));
                    let rhs_val = Self::load_reg(builder, reg_base, u32::from(rhs));

                    let mask = builder.ins().iconst(types::I64, Self::MASK_KIND as i64);
                    let int_tag = builder.ins().iconst(types::I64, Self::MASK_INT32 as i64);
                    let lhs_tag = builder.ins().band(lhs_val, mask);
                    let rhs_tag = builder.ins().band(rhs_val, mask);
                    let lhs_is_int = builder.ins().icmp(cranelift_codegen::ir::condcodes::IntCC::Equal, lhs_tag, int_tag);
                    let rhs_is_int = builder.ins().icmp(cranelift_codegen::ir::condcodes::IntCC::Equal, rhs_tag, int_tag);
                    let both_int = builder.ins().band(lhs_is_int, rhs_is_int);

                    let fast_block = builder.create_block();
                    let slow_block = builder.create_block();
                    builder.ins().brif(both_int, fast_block, &[], slow_block, &[]);

                    // Fast path: compare as i32 (lower 32 bits).
                    builder.switch_to_block(fast_block);
            
                    let lhs_i32 = builder.ins().ireduce(types::I32, lhs_val);
                    let rhs_i32 = builder.ins().ireduce(types::I32, rhs_val);
                    let is_less = builder.ins().icmp(
                        cranelift_codegen::ir::condcodes::IntCC::SignedLessThan,
                        lhs_i32,
                        rhs_i32,
                    );
                    let fast_continue = builder.create_block();
                    // If lhs < rhs, don't jump (continue). Else jump to target.
                    builder.ins().brif(is_less, fast_continue, &[], target, &[]);
            

                    // Slow path: call helper.
                    builder.switch_to_block(slow_block);
            
                    let l = i32const(builder, u32::from(lhs));
                    let r = i32const(builder, u32::from(rhs));
                    let result = builder.ins().call(not_lt_ref, &[ctx_ptr, l, r]);
                    let tag = builder.inst_results(result)[0];

                    let two = builder.ins().iconst(types::I64, 2);
                    let is_error = builder.ins().icmp(
                        cranelift_codegen::ir::condcodes::IntCC::Equal, tag, two,
                    );
                    let not_error = builder.create_block();
                    builder.ins().brif(is_error, error_block, &[], not_error, &[]);
            
                    builder.switch_to_block(not_error);

                    let one = builder.ins().iconst(types::I64, 1);
                    let should_jump = builder.ins().icmp(
                        cranelift_codegen::ir::condcodes::IntCC::Equal, tag, one,
                    );
                    builder.ins().brif(should_jump, target, &[], fast_continue, &[]);

                    // Continue block after either path.
                    builder.switch_to_block(fast_continue);
                }
                Instruction::CheckReturn => {
                    // Handled with Return.
                }
                Instruction::Return => {
                    let result = builder.ins().call(ret_ref, &[ctx_ptr]);
                    let tag = builder.inst_results(result)[0];
                    builder.ins().return_(&[tag]);
                    terminated = true;
                }
                _ => {
                    let err = builder.ins().iconst(types::I64, 2);
                    builder.ins().return_(&[err]);
                    terminated = true;
                }
            }
        }

        if !terminated {
            let zero = builder.ins().iconst(types::I64, 0);
            builder.ins().return_(&[zero]);
        }

        // Finalize the error block.
        builder.switch_to_block(error_block);
        let err_tag = builder.ins().iconst(types::I64, 2);
        builder.ins().return_(&[err_tag]);

        // Seal all blocks at once. This is simpler than tracking individual
        // block predecessors, especially with backward jumps (loops).
        builder.seal_all_blocks();
    }
}
