//! Cranelift-based JIT compiler for Boa bytecode.
//!
//! The compiler translates a [`CodeBlock`] into a native function that operates
//! on the same `Context` and stack that the interpreter uses. This first version
//! eliminates dispatch overhead but still calls back into Rust helpers for all
//! value operations.

use cranelift_codegen::{
    ir::{types, AbiParam, Block, Function, InstBuilder, Type, UserFuncName, Value},
    settings::{self, Configurable},
};
use cranelift_frontend::{FunctionBuilder, FunctionBuilderContext};
use cranelift_jit::{JITBuilder, JITModule};
use cranelift_module::{FuncId, Linkage, Module};
use std::collections::HashMap;
use std::ops::ControlFlow;

use crate::{
    Context, JsValue,
    vm::{
        CodeBlock, CompletionRecord,
        opcode::{Address, Instruction, InstructionIterator, Opcode},
    },
};

use super::helpers;

/// Raw JIT function pointer. Returns a tag: 0=Continue, 1=Break(Return), 2=Break(Throw).
/// The actual values (return value, exception) are communicated via Context.
type RawJitFn = unsafe extern "C" fn(*mut Context) -> u64;

/// A compiled JIT function that can be called in place of interpreting bytecode.
///
/// Wraps the raw function pointer with a safe calling convention.
#[derive(Clone, Copy)]
pub(crate) struct JitFn(RawJitFn);

impl std::fmt::Debug for JitFn {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("JitFn")
            .field(&(self.0 as *const ()))
            .finish()
    }
}

impl JitFn {
    /// Call the JIT-compiled function.
    ///
    /// The JIT function returns a tag:
    /// - 0: `handle_return` returned `Continue` — frame was popped, result
    ///   pushed on the stack. This is the normal case.
    /// - 1: `handle_return` returned `Break(Return(value))` — `exit_early`
    ///   was set, value is in the `CompletionRecord`.
    /// - 2: An exception occurred — stored in `pending_exception`.
    pub(crate) fn call(self, context: &mut Context) -> CompletionRecord {
        // SAFETY: The raw function was generated by Cranelift with the correct
        // signature (one pointer arg, returns u64).
        let tag = unsafe { (self.0)(context as *mut Context) };
        match tag {
            0 => {
                // Normal return — handle_return already popped the frame and
                // pushed the result on the stack. Return Normal completion.
                CompletionRecord::Normal(JsValue::undefined())
            }
            1 => {
                // exit_early was set — handle_return returned Break(Return(value)).
                CompletionRecord::Return(context.vm.take_return_value())
            }
            _ => {
                // Exception.
                CompletionRecord::Throw(
                    context
                        .vm
                        .pending_exception
                        .take()
                        .unwrap_or_else(|| {
                            crate::JsNativeError::error()
                                .with_message("JIT: unknown error")
                                .into()
                        }),
                )
            }
        }
    }
}

/// Holds the [`FuncId`]s for the runtime helper functions that JIT code calls.
struct HelperFuncs {
    store_zero: FuncId,
    store_one: FuncId,
    store_int8: FuncId,
    store_int16: FuncId,
    store_int32: FuncId,
    get_argument: FuncId,
    move_: FuncId,
    set_accumulator: FuncId,
    push_from_register: FuncId,
    pop_into_register: FuncId,
    add: FuncId,
    sub: FuncId,
    mul: FuncId,
    bit_or: FuncId,
    inc: FuncId,
    increment_loop_iteration: FuncId,
    not_less_than: FuncId,
    check_return_and_return: FuncId,
}

/// The JIT compiler. Holds the Cranelift module and compiled function cache.
pub(crate) struct JitCompiler {
    module: JITModule,
    ptr_type: Type,
    helpers: HelperFuncs,
    func_counter: u32,
}

impl std::fmt::Debug for JitCompiler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("JitCompiler")
            .field("func_counter", &self.func_counter)
            .finish_non_exhaustive()
    }
}

impl JitCompiler {
    /// Create a new JIT compiler for the host architecture.
    pub(crate) fn new() -> Result<Self, String> {
        let mut flag_builder = settings::builder();
        flag_builder
            .set("opt_level", "speed")
            .map_err(|e| e.to_string())?;

        let isa_builder =
            cranelift_native::builder().map_err(|e| format!("host ISA not supported: {e}"))?;
        let isa = isa_builder
            .finish(settings::Flags::new(flag_builder))
            .map_err(|e| e.to_string())?;

        let ptr_type = isa.pointer_type();

        let mut builder = JITBuilder::with_isa(isa, cranelift_module::default_libcall_names());

        // Register helper function symbols.
        let syms: &[(&str, *const u8)] = &[
            ("jit_store_zero", helpers::jit_store_zero as *const u8),
            ("jit_store_one", helpers::jit_store_one as *const u8),
            ("jit_store_int8", helpers::jit_store_int8 as *const u8),
            ("jit_store_int16", helpers::jit_store_int16 as *const u8),
            ("jit_store_int32", helpers::jit_store_int32 as *const u8),
            ("jit_get_argument", helpers::jit_get_argument as *const u8),
            ("jit_move", helpers::jit_move as *const u8),
            ("jit_set_accumulator", helpers::jit_set_accumulator as *const u8),
            ("jit_push_from_register", helpers::jit_push_from_register as *const u8),
            ("jit_pop_into_register", helpers::jit_pop_into_register as *const u8),
            ("jit_add", helpers::jit_add as *const u8),
            ("jit_sub", helpers::jit_sub as *const u8),
            ("jit_mul", helpers::jit_mul as *const u8),
            ("jit_bit_or", helpers::jit_bit_or as *const u8),
            ("jit_inc", helpers::jit_inc as *const u8),
            ("jit_increment_loop_iteration", helpers::jit_increment_loop_iteration as *const u8),
            ("jit_not_less_than", helpers::jit_not_less_than as *const u8),
            ("jit_check_return_and_return", helpers::jit_check_return_and_return as *const u8),
        ];
        for &(name, ptr) in syms {
            builder.symbol(name, ptr);
        }

        let mut module = JITModule::new(builder);
        let helpers = Self::declare_helpers(&mut module, ptr_type)?;

        Ok(Self {
            module,
            ptr_type,
            helpers,
            func_counter: 0,
        })
    }

    fn declare_helpers(module: &mut JITModule, ptr: Type) -> Result<HelperFuncs, String> {
        // Signature builders
        let sig_void_1 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.params.push(AbiParam::new(types::I32));
            s
        };
        let sig_void_2 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s
        };
        let sig_void_3 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s
        };
        let sig_ret64_0 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.returns.push(AbiParam::new(types::I64));
            s
        };
        let sig_ret64_2 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s.returns.push(AbiParam::new(types::I64));
            s
        };
        let sig_ret64_3 = {
            let mut s = module.make_signature();
            s.params.push(AbiParam::new(ptr));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s.params.push(AbiParam::new(types::I32));
            s.returns.push(AbiParam::new(types::I64));
            s
        };

        let d = |module: &mut JITModule, name, sig: &cranelift_codegen::ir::Signature| {
            module
                .declare_function(name, Linkage::Import, sig)
                .map_err(|e| e.to_string())
        };

        Ok(HelperFuncs {
            store_zero: d(module, "jit_store_zero", &sig_void_1)?,
            store_one: d(module, "jit_store_one", &sig_void_1)?,
            store_int8: d(module, "jit_store_int8", &sig_void_2)?,
            store_int16: d(module, "jit_store_int16", &sig_void_2)?,
            store_int32: d(module, "jit_store_int32", &sig_void_2)?,
            get_argument: d(module, "jit_get_argument", &sig_void_2)?,
            move_: d(module, "jit_move", &sig_void_2)?,
            set_accumulator: d(module, "jit_set_accumulator", &sig_void_1)?,
            push_from_register: d(module, "jit_push_from_register", &sig_void_1)?,
            pop_into_register: d(module, "jit_pop_into_register", &sig_void_1)?,
            add: d(module, "jit_add", &sig_ret64_3)?,
            sub: d(module, "jit_sub", &sig_ret64_3)?,
            mul: d(module, "jit_mul", &sig_ret64_3)?,
            bit_or: d(module, "jit_bit_or", &sig_ret64_3)?,
            inc: d(module, "jit_inc", &sig_ret64_2)?,
            increment_loop_iteration: d(module, "jit_increment_loop_iteration", &sig_ret64_0)?,
            not_less_than: d(module, "jit_not_less_than", &sig_ret64_2)?,
            check_return_and_return: d(module, "jit_check_return_and_return", &sig_ret64_0)?,
        })
    }

    /// Compile a [`CodeBlock`] into a native function.
    pub(crate) fn compile(&mut self, code: &CodeBlock) -> Option<JitFn> {
        if !super::can_compile(code) {
            return None;
        }

        let name = format!("jit_fn_{}", self.func_counter);
        self.func_counter += 1;

        let mut sig = self.module.make_signature();
        sig.params.push(AbiParam::new(self.ptr_type));
        sig.returns.push(AbiParam::new(types::I64));

        let func_id = self
            .module
            .declare_function(&name, Linkage::Local, &sig)
            .expect("declare function");

        let mut func =
            Function::with_name_signature(UserFuncName::testcase(&name), sig.clone());

        let mut func_ctx = FunctionBuilderContext::new();
        {
            let mut builder = FunctionBuilder::new(&mut func, &mut func_ctx);

            let entry_block = builder.create_block();
            builder.append_block_params_for_function_params(entry_block);
            builder.switch_to_block(entry_block);

            let ctx_ptr = builder.block_params(entry_block)[0];

            self.translate_body(&mut builder, ctx_ptr, code, entry_block);

            builder.finalize();
        }

        let mut ctx = cranelift_codegen::Context::for_function(func);
        self.module
            .define_function(func_id, &mut ctx)
            .expect("define function");
        self.module.clear_context(&mut ctx);
        self.module.finalize_definitions().expect("finalize");

        let code_ptr = self.module.get_finalized_function(func_id);

        // SAFETY: The generated code has signature (ptr) -> i64, matching RawJitFn.
        let raw: RawJitFn = unsafe { std::mem::transmute(code_ptr) };
        Some(JitFn(raw))
    }

    /// Emit a call to a fallible helper (returns i64: 0=ok, nonzero=error).
    /// On error, returns from the JIT function with error tag 2.
    fn emit_fallible_call(
        builder: &mut FunctionBuilder<'_>,
        func_ref: cranelift_codegen::ir::FuncRef,
        args: &[Value],
        error_block: Block,
    ) {
        let result = builder.ins().call(func_ref, args);
        let tag = builder.inst_results(result)[0];
        let zero = builder.ins().iconst(types::I64, 0);
        let ok = builder.ins().icmp(cranelift_codegen::ir::condcodes::IntCC::Equal, tag, zero);

        let continue_block = builder.create_block();
        builder.ins().brif(ok, continue_block, &[], error_block, &[]);
        builder.seal_block(continue_block);
        builder.switch_to_block(continue_block);
    }

    /// Translate the bytecode body into Cranelift IR.
    fn translate_body(
        &mut self,
        builder: &mut FunctionBuilder<'_>,
        ctx_ptr: Value,
        code: &CodeBlock,
        entry_block: Block,
    ) {
        // Import helper function references.
        let store_zero_ref = self.module.declare_func_in_func(self.helpers.store_zero, builder.func);
        let store_one_ref = self.module.declare_func_in_func(self.helpers.store_one, builder.func);
        let store_int8_ref = self.module.declare_func_in_func(self.helpers.store_int8, builder.func);
        let store_int16_ref = self.module.declare_func_in_func(self.helpers.store_int16, builder.func);
        let store_int32_ref = self.module.declare_func_in_func(self.helpers.store_int32, builder.func);
        let get_arg_ref = self.module.declare_func_in_func(self.helpers.get_argument, builder.func);
        let move_ref = self.module.declare_func_in_func(self.helpers.move_, builder.func);
        let set_acc_ref = self.module.declare_func_in_func(self.helpers.set_accumulator, builder.func);
        let push_reg_ref = self.module.declare_func_in_func(self.helpers.push_from_register, builder.func);
        let pop_reg_ref = self.module.declare_func_in_func(self.helpers.pop_into_register, builder.func);
        let add_ref = self.module.declare_func_in_func(self.helpers.add, builder.func);
        let sub_ref = self.module.declare_func_in_func(self.helpers.sub, builder.func);
        let mul_ref = self.module.declare_func_in_func(self.helpers.mul, builder.func);
        let bit_or_ref = self.module.declare_func_in_func(self.helpers.bit_or, builder.func);
        let inc_ref = self.module.declare_func_in_func(self.helpers.inc, builder.func);
        let inc_loop_ref = self.module.declare_func_in_func(self.helpers.increment_loop_iteration, builder.func);
        let not_lt_ref = self.module.declare_func_in_func(self.helpers.not_less_than, builder.func);
        let ret_ref = self.module.declare_func_in_func(self.helpers.check_return_and_return, builder.func);

        // Error block: returns error tag (2) to signal exception to caller.
        let error_block = builder.create_block();

        // Phase 1: Pre-scan bytecode to find jump targets and create blocks.
        let mut block_map: HashMap<u32, Block> = HashMap::new();
        {
            let iter = InstructionIterator::new(&code.bytecode);
            for (_pc, _opcode, instruction) in iter {
                match &instruction {
                    Instruction::Jump { address } => {
                        let target = address.as_u32();
                        block_map
                            .entry(target)
                            .or_insert_with(|| builder.create_block());
                    }
                    Instruction::JumpIfNotLessThan { address, .. } => {
                        let target = address.as_u32();
                        block_map
                            .entry(target)
                            .or_insert_with(|| builder.create_block());
                    }
                    _ => {}
                }
            }
        }

        // We also need blocks for the instruction AFTER a conditional jump
        // (the fall-through path). And for the instruction after the jump target
        // when it's not already a block boundary.
        // Actually, for conditional jumps, the fall-through is just the next
        // instruction in the current block — we only need blocks where jumps
        // LAND (forward or backward).

        // Phase 2: Emit code. When we reach a PC that's a jump target,
        // transition to its block.
        let iter = InstructionIterator::new(&code.bytecode);
        let mut terminated = false;

        for (pc, _opcode, instruction) in iter {
            // Check if this PC is a jump target — if so, transition to its block.
            if let Some(&target_block) = block_map.get(&(pc as u32)) {
                if !terminated {
                    // Fall through from previous block.
                    builder.ins().jump(target_block, &[]);
                }
                builder.switch_to_block(target_block);
                terminated = false;
            }

            if terminated {
                continue;
            }

            let i32const =
                |builder: &mut FunctionBuilder<'_>, val: u32| -> Value {
                    builder.ins().iconst(types::I32, i64::from(val))
                };

            match instruction {
                Instruction::StoreZero { dst } => {
                    let d = i32const(builder, u32::from(dst));
                    builder.ins().call(store_zero_ref, &[ctx_ptr, d]);
                }
                Instruction::StoreOne { dst } => {
                    let d = i32const(builder, u32::from(dst));
                    builder.ins().call(store_one_ref, &[ctx_ptr, d]);
                }
                Instruction::StoreInt8 { dst, value } => {
                    let d = i32const(builder, u32::from(dst));
                    let v = builder.ins().iconst(types::I32, i64::from(value));
                    builder.ins().call(store_int8_ref, &[ctx_ptr, d, v]);
                }
                Instruction::StoreInt16 { dst, value } => {
                    let d = i32const(builder, u32::from(dst));
                    let v = builder.ins().iconst(types::I32, i64::from(value));
                    builder.ins().call(store_int16_ref, &[ctx_ptr, d, v]);
                }
                Instruction::StoreInt32 { dst, value } => {
                    let d = i32const(builder, u32::from(dst));
                    let v = builder.ins().iconst(types::I32, i64::from(value));
                    builder.ins().call(store_int32_ref, &[ctx_ptr, d, v]);
                }
                Instruction::GetArgument { index, dst } => {
                    let idx = i32const(builder, u32::from(index));
                    let d = i32const(builder, u32::from(dst));
                    builder.ins().call(get_arg_ref, &[ctx_ptr, idx, d]);
                }
                Instruction::Move { dst, src } => {
                    let d = i32const(builder, u32::from(dst));
                    let s = i32const(builder, u32::from(src));
                    builder.ins().call(move_ref, &[ctx_ptr, d, s]);
                }
                Instruction::SetAccumulator { src } => {
                    let s = i32const(builder, u32::from(src));
                    builder.ins().call(set_acc_ref, &[ctx_ptr, s]);
                }
                Instruction::PushFromRegister { src } => {
                    let s = i32const(builder, u32::from(src));
                    builder.ins().call(push_reg_ref, &[ctx_ptr, s]);
                }
                Instruction::PopIntoRegister { dst } => {
                    let d = i32const(builder, u32::from(dst));
                    builder.ins().call(pop_reg_ref, &[ctx_ptr, d]);
                }
                Instruction::Add { dst, lhs, rhs } => {
                    let d = i32const(builder, u32::from(dst));
                    let l = i32const(builder, u32::from(lhs));
                    let r = i32const(builder, u32::from(rhs));
                    Self::emit_fallible_call(builder, add_ref, &[ctx_ptr, d, l, r], error_block);
                }
                Instruction::Sub { dst, lhs, rhs } => {
                    let d = i32const(builder, u32::from(dst));
                    let l = i32const(builder, u32::from(lhs));
                    let r = i32const(builder, u32::from(rhs));
                    Self::emit_fallible_call(builder, sub_ref, &[ctx_ptr, d, l, r], error_block);
                }
                Instruction::Mul { dst, lhs, rhs } => {
                    let d = i32const(builder, u32::from(dst));
                    let l = i32const(builder, u32::from(lhs));
                    let r = i32const(builder, u32::from(rhs));
                    Self::emit_fallible_call(builder, mul_ref, &[ctx_ptr, d, l, r], error_block);
                }
                Instruction::BitOr { dst, lhs, rhs } => {
                    let d = i32const(builder, u32::from(dst));
                    let l = i32const(builder, u32::from(lhs));
                    let r = i32const(builder, u32::from(rhs));
                    Self::emit_fallible_call(builder, bit_or_ref, &[ctx_ptr, d, l, r], error_block);
                }
                Instruction::Inc { dst, src } => {
                    let d = i32const(builder, u32::from(dst));
                    let s = i32const(builder, u32::from(src));
                    Self::emit_fallible_call(builder, inc_ref, &[ctx_ptr, d, s], error_block);
                }
                Instruction::IncrementLoopIteration => {
                    Self::emit_fallible_call(builder, inc_loop_ref, &[ctx_ptr], error_block);
                }
                Instruction::Jump { address } => {
                    let target = block_map[&address.as_u32()];
                    builder.ins().jump(target, &[]);
                    terminated = true;
                }
                Instruction::JumpIfNotLessThan { lhs, rhs, address } => {
                    let l = i32const(builder, u32::from(lhs));
                    let r = i32const(builder, u32::from(rhs));
                    let result = builder.ins().call(not_lt_ref, &[ctx_ptr, l, r]);
                    let tag = builder.inst_results(result)[0];

                    // tag: 0 = lhs < rhs (don't jump), 1 = lhs >= rhs (jump), 2 = error
                    let two = builder.ins().iconst(types::I64, 2);
                    let is_error = builder.ins().icmp(
                        cranelift_codegen::ir::condcodes::IntCC::Equal,
                        tag,
                        two,
                    );

                    // Check for error first.
                    let not_error_block = builder.create_block();
                    builder.ins().brif(is_error, error_block, &[], not_error_block, &[]);
                    builder.seal_block(not_error_block);
                    builder.switch_to_block(not_error_block);

                    // Now check if we should jump (tag == 1 means lhs >= rhs).
                    let one = builder.ins().iconst(types::I64, 1);
                    let should_jump = builder.ins().icmp(
                        cranelift_codegen::ir::condcodes::IntCC::Equal,
                        tag,
                        one,
                    );
                    let target = block_map[&address.as_u32()];
                    let fall_through = builder.create_block();
                    builder.ins().brif(should_jump, target, &[], fall_through, &[]);
                    builder.seal_block(fall_through);
                    builder.switch_to_block(fall_through);
                }
                Instruction::CheckReturn => {
                    // Handled with Return.
                }
                Instruction::Return => {
                    let result = builder.ins().call(ret_ref, &[ctx_ptr]);
                    let tag = builder.inst_results(result)[0];
                    builder.ins().return_(&[tag]);
                    terminated = true;
                }
                _ => {
                    let err = builder.ins().iconst(types::I64, 2);
                    builder.ins().return_(&[err]);
                    terminated = true;
                }
            }
        }

        if !terminated {
            let zero = builder.ins().iconst(types::I64, 0);
            builder.ins().return_(&[zero]);
        }

        // Finalize the error block.
        builder.switch_to_block(error_block);
        let err_tag = builder.ins().iconst(types::I64, 2);
        builder.ins().return_(&[err_tag]);

        // Seal the entry block and error block.
        builder.seal_block(entry_block);
        builder.seal_block(error_block);

        // Seal any jump target blocks that weren't sealed yet.
        for (_, &block) in &block_map {
            builder.seal_block(block);
        }
    }
}
